name: restaurant_mobile_app
description: A new Flutter project.
publish_to: 'none'
version: 2.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shimmer: ^3.0.0
  flutter_svg: ^2.0.7
  shared_preferences: ^2.2.2
  carousel_slider: ^4.2.1
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.4.9
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Index24.png
    - assets/Create24.png
    - assets/Edit24.png
    - assets/remove24.png
    - assets/NotFound.svg
    - assets/CMenuImg1.jpg
    - assets/Food1.jpg
    - assets/Food2.jpg
    - assets/Food3.jpg
    - assets/Food4.jpg
    - assets/DragLeft.jpg
    - assets/UndoLeft.jpg
    - .env
    - assets/gitProfPic.jpg
    - assets/githubIcon.png
    - assets/linkedInIcon.png
  fonts:
    - family: Quicksand
      fonts: 
        - asset: fonts/Quicksand-Bold.ttf
        - asset: fonts/Quicksand-Light.ttf
        - asset: fonts/Quicksand-Medium.ttf
        - asset: fonts/Quicksand-SemiBold.ttf
        - asset: fonts/Quicksand-Regular.ttf
